// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhTEoXFIMSoAVnL4xSqraw6DYRYP5cuY',
    appId: '1:590690622893:web:4ef7315348871f7598d524',
    messagingSenderId: '590690622893',
    projectId: 'connect-master-flutter-0518',
    authDomain: 'connect-master-flutter-0518.firebaseapp.com',
    storageBucket: 'connect-master-flutter-0518.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPeQ3ggKSSs8qtntpzk8iBNEkdK49O1GE',
    appId: '1:590690622893:android:dd9627581d13b04f98d524',
    messagingSenderId: '590690622893',
    projectId: 'connect-master-flutter-0518',
    storageBucket: 'connect-master-flutter-0518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANelbk0iC-IYK_xs1CRzauYOR-7JZslBY',
    appId: '1:590690622893:ios:a72119dc85c1e8a498d524',
    messagingSenderId: '590690622893',
    projectId: 'connect-master-flutter-0518',
    storageBucket: 'connect-master-flutter-0518.appspot.com',
    iosClientId: '590690622893-o4geshc6tncodpttcp9dj79cin49dqml.apps.googleusercontent.com',
    iosBundleId: 'com.example.story',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANelbk0iC-IYK_xs1CRzauYOR-7JZslBY',
    appId: '1:590690622893:ios:a72119dc85c1e8a498d524',
    messagingSenderId: '590690622893',
    projectId: 'connect-master-flutter-0518',
    storageBucket: 'connect-master-flutter-0518.appspot.com',
    iosClientId: '590690622893-o4geshc6tncodpttcp9dj79cin49dqml.apps.googleusercontent.com',
    iosBundleId: 'com.example.story',
  );
}
